name: Terradatum RETS Client CI

on:
  push:
    branches:
      - main
    paths:
      - '**/src/**'
      - '**/pom.xml'
      - '.github/maven/settings.xml'
      - '.github/workflows/main.yml'
      - 'prepare.sh'
      - 'publish.sh'
      - '.releaserc.json'

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # required for commit analysis - it needs access to full history
          ref: ${{ github.event.inputs.ref }} # required to build/run on non-default branches from workflow_dispatch events

      ## Setup Java and retrieve the version from the pom.xml file
      - name: Setup Java 15
        uses: actions/setup-java@v1
        with:
          java-version: 15
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        id: semantic_release
        with:
          semantic_version: 16
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            @semantic-release/exec
            conventional-changelog-conventionalcommits
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current version from pom.xml
        uses: terradatum/semver-action@v1
        id: get_version
        with:
          package-manager-type: maven
